### ISSUE TITLE
Error when using

### ISSUE THREAD

**Issue by ameeno** [zeshuaro/LinkedRW#11]
removed.

**Comment by zeshuaro** [comment]
I've made some changes to handle the education section scraping. Update `linkedrw` and try it again. Feel free to reopen the issue if it still doesn't work.

**Comment by ameeno** [comment]
Hello man, I've updated to the latest 1.1.2 version.

I have tried also with chromedriver & gecko, still bugs out same as before.

**Comment by zeshuaro** [comment]
Can you either email me the html page of your LinkedIn profile or post a link to the html page?

**Comment by ameeno** [comment]
Sure, Where do i find your email?

**Comment by zeshuaro** [comment]
zeshuaro@gmail.com

**Comment by zeshuaro** [comment]
It looks like it was stuck for loading a page. When the script was running, can you see that the browser navigating to your profile page?

Have you also tried the following?
* Keep the browser window on top when the script is running
* Increase the timeout by specifying `-t/--timeout` option

**Comment by ameeno** [comment]
I did see the profile scrolling, but I will try with timeoutSent from my Samsung Galaxy smartphone.
-------- Original message --------From: zeshuaro <notifications@github.com> Date: 03/06/2019  11:49  (GMT+00:00) To: zeshuaro/LinkedRW <LinkedRW@noreply.github.com> Cc: Arun Shah <fastah@gmail.com>, Author <author@noreply.github.com> Subject: Re: [zeshuaro/LinkedRW] Error when using (#11) It looks like it was stuck for loading a page. When the script was running, can you see that the browser navigating to your profile page?
Have you also tried the following?

Keep the browser window on top when the script is running
Increase the timeout by specifying -t/--timeout option


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/zeshuaro/LinkedRW/issues/11?email_source=notifications\u0026email_token=AAC64LNBUFCIV3MVKLDFJJLPYTZMVA5CNFSM4HSC3562YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWZA5II#issuecomment-498208417",
"url": "https://github.com/zeshuaro/LinkedRW/issues/11?email_source=notifications\u0026email_token=AAC64LNBUFCIV3MVKLDFJJLPYTZMVA5CNFSM4HSC3562YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWZA5II#issuecomment-498208417",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ameeno** [comment]
Hello there.

I wondered if you have any progress update on this.

It seems to refer to the volunteering section.

The script just seems to die whatever Browser/timeout I am using.

**Comment by zeshuaro** [comment]
I am trying to reproduce your error

**Comment by ameeno** [comment]
i get selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".mt1.inline-block.t-18.t-black.t-normal"}
  (Session info: chrome=75.0.3770.80) when i tried to use version 1.1.5.

not working i tried long timeout.

**Comment by zeshuaro** [comment]
Working on it, will make an update over this weekend
